services:
  k-01:
    image: confluentinc/cp-kafka:7.5.10
    container_name: k-01 
    environment:
      # MUST HAVE FOR KRAFT MODE
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@k-01:9093,2@k-02:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      ####
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'CONTROLLER://k-01:9093,PLAINTEXT://k-01:9092,PLAINTEXT_HOST://0.0.0.0:19094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://k-01:9092,PLAINTEXT_HOST://localhost:19094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      KAFKA_JMX_PORT: 9090
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    ports:
      - '19094:9094'

  k-02:
    image: confluentinc/cp-kafka:7.5.10
    container_name: k-02 
    environment:
      # MUST HAVE FOR KRAFT MODE
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@k-01:9093,2@k-02:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      ####
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'CONTROLLER://k-02:9093,PLAINTEXT://k-02:9092,PLAINTEXT_HOST://0.0.0.0:29094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://k-02:9092,PLAINTEXT_HOST://localhost:29094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      KAFKA_JMX_PORT: 9090
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    ports:
      - '29094:9094'
  k-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: k-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: s2lh
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: k-01:9092,k-02:9092
    ports:
      - "18080:8080" # Web UI